apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: vcluster-<environment>
  namespace: flux-system
spec:
  interval: 10m0s
  prune: true 
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./vcluster-template"
  wait: true
  postBuild:
    substitute:
      env: dev # Change this value for each environment
